export { default as Skeleton } from "./Skeleton";
export { default as CardSkeleton } from "./CardSkeleton";
export { default as HomeSkeleton } from "./HomeSkeleton";
export { default as LoginSkeleton } from "./LoginSkeleton";
export { default as RegisterSkeleton } from "./RegisterSkeleton";
export { default as ExercisesSkeleton } from "./ExercisesSkeleton";
export { default as FavoriteSkeleton } from "./FavoriteSkeleton";
export { default as SurveySkeleton } from "./SurveySkeleton";
export { default as DetailSkeleton } from "./DetailSkeleton";
